
###
### ndk-module file generated by CDep
### DO NOT EDIT
###
cdep_exploded_root:=/usr/local/google/home/jomof/.cdep/exploded
###
### Add header-only dependency for CDep module: com.github.jomof:boost:1.0.63-rev24
###
LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE:=boost
CDEP_STATIC_LIBRARY_EXPORTED:=
coordinate_group_id:=com.github.jomof
coordinate_artifact_id:=boost
coordinate_version:=1.0.63-rev24
exploded_archive_tail:=$(coordinate_group_id)/$(coordinate_artifact_id)/$(coordinate_version)
exploded_archive_folder:=$(cdep_exploded_root)/$(exploded_archive_tail)
ifeq ($(wildcard $(exploded_archive_folder)/boost_1_63_0.zip/completion_sentinel),)
  $(info CDep downloading https://github.com/jomof/boost/releases/download/1.0.63-rev24/boost_1_63_0.zip)
  $(shell /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -classpath /usr/local/google/home/jomof/.cdep/bootstrap/downloads/926747844/cdep-0.8.20.jar io.cdep.CDep --working-folder /usr/local/google/home/jomof/projects/ndk-build-meet-cdep/. fetch-archive com.github.jomof:boost:1.0.63-rev24 https://github.com/jomof/boost/releases/download/1.0.63-rev24/boost_1_63_0.zip 142660118 97ce6635df1f44653a597343cd5757bb8b6b992beb3720f5fc761e3644bcbe7b)
endif
LOCAL_EXPORT_C_INCLUDES+=$(exploded_archive_folder)/boost_1_63_0.zip/boost_1_63_0
include $(BUILD_STATIC_LIBRARY)